/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ycloud_audio_AudioPlaybackRateProcessor */

#ifndef _Included_com_ycloud_audio_AudioPlaybackRateProcessor
#define _Included_com_ycloud_audio_AudioPlaybackRateProcessor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ycloud_audio_AudioPlaybackRateProcessor
 * Method:    create
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_create
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_ycloud_audio_AudioPlaybackRateProcessor
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ycloud_audio_AudioPlaybackRateProcessor
 * Method:    push
 * Signature: (J[S[S)I
 */
JNIEXPORT void JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_push
  (JNIEnv *, jobject, jlong, jbyteArray, jint len);


/*
 * Class:     com_ycloud_audio_AudioPlaybackRateProcessor
 * Method:    pull
 * Signature: (J[S[S)I
 */
JNIEXPORT jint JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_pull
  (JNIEnv *, jobject, jlong, jbyteArray, jint offset, jint len);

/*
 * Class:     com_ycloud_audio_AudioPlaybackRateProcessor
 * Method:    setRate
 * Signature: (J[S[S)I
 */
JNIEXPORT void JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_setRate
  (JNIEnv *, jobject, jlong, jfloat);


JNIEXPORT void JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_flush
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_clear
  (JNIEnv *, jobject, jlong);

JNIEXPORT int JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_numOfMSAvailable
  (JNIEnv *, jobject, jlong);

JNIEXPORT int JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_numOfMSUnprocess
  (JNIEnv *, jobject, jlong);

JNIEXPORT int JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_numOfBytesAvailable
  (JNIEnv *, jobject, jlong);

JNIEXPORT int JNICALL Java_com_ycloud_audio_AudioPlaybackRateProcessor_numOfBytesUnprocess
  (JNIEnv *, jobject, jlong);

JNIEXPORT jlong JNICALL Java_com_ycloud_audio_FFTProcessor_create
  (JNIEnv *env, jobject thiz, jint);

JNIEXPORT void JNICALL Java_com_ycloud_audio_FFTProcessor_destroy
  (JNIEnv *env, jobject thiz, jlong);

JNIEXPORT void JNICALL Java_com_ycloud_audio_FFTProcessor_flush
  (JNIEnv *env, jobject thiz, jlong);

JNIEXPORT void JNICALL Java_com_ycloud_audio_FFTProcessor_process
  (JNIEnv *env, jobject thiz, jlong, jbyteArray, jint offset, jint len, jint stride);

JNIEXPORT jint JNICALL Java_com_ycloud_audio_FFTProcessor_frequencyData
  (JNIEnv *, jobject, jlong, jfloatArray, jint len);

  void initAudio(JNIEnv* env);

#ifdef __cplusplus
}
#endif
#endif
