/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ycloud_mediarecord_MediaNative */

#ifndef _Included_com_ycloud_mediarecord_MediaNative
#define _Included_com_ycloud_mediarecord_MediaNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL jni_media_recorder_create_ctx (JNIEnv *env, jobject object);
JNIEXPORT void JNICALL jni_media_recorder_destroy_ctx(JNIEnv *env, jobject object, jlong handle);

JNIEXPORT jint JNICALL jni_media_recorder_get_params(JNIEnv *env, jobject object, jlong handle, jobject params);

JNIEXPORT jint JNICALL jni_media_recorder_set_params(JNIEnv *env, jobject object, jlong handle, jobject params);


JNIEXPORT jint JNICALL jni_media_recorder_start(JNIEnv *env, jobject object, jlong handle);

JNIEXPORT jint JNICALL jni_media_recorder_stop(JNIEnv *env, jobject object, jlong handle, jint force);

JNIEXPORT jint JNICALL jni_media_recorder_receive_video_data(JNIEnv *env, jobject object, jlong handle, jbyteArray data, jint size, jlong pts);

JNIEXPORT jint JNICALL jni_media_recorder_receive_video_data2(JNIEnv *env, jobject object, jlong handle, jbyteArray data, jint size, jlong pts);

JNIEXPORT jint JNICALL jni_media_recorder_receive_audio_data
  (JNIEnv *env, jobject object, jlong handle, jbyteArray data, jint size, jlong pts);
JNIEXPORT jstring JNICALL jni_media_process(JNIEnv *env, jobject object, jint cmd_type, jstring cmd);
JNIEXPORT jstring JNICALL jni_get_frame_filename(JNIEnv *env, jobject object, jstring path, jint number);  
JNIEXPORT jlong JNICALL jni_media_create_decoder(JNIEnv *env, jobject object, jstring videoPath, jobject params);
  
JNIEXPORT jint JNICALL jni_media_read_frame(JNIEnv *env, jobject object, jlong handle, jintArray rgbOut);

JNIEXPORT jlong JNICALL jni_media_read_frame_pts(JNIEnv *env, jobject object, jlong handle, jintArray rgbOut);
 
JNIEXPORT jint JNICALL jni_media_get_video_width(JNIEnv *env, jobject object, jlong handle);
  
JNIEXPORT jint JNICALL jni_media_get_video_height(JNIEnv *env, jobject object, jlong handle);
  
JNIEXPORT void JNICALL jni_media_stop_decoder(JNIEnv *env, jobject object, jlong handle);
  
JNIEXPORT void JNICALL jni_cancel_media_process(JNIEnv *env, jobject object);
JNIEXPORT jobject JNICALL jni_getMediaRecorderNativeSSInfo(JNIEnv *env, jclass obj, jlong handle,jobject ssInfoObj);


#ifdef __cplusplus
}
#endif
#endif
