/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_grafika_gles_NativeJniCall */

#ifndef _Included_com_yy_mediaframeworks_gpuimage_adapter_GLESNativeTools
#define _Included_com_yy_mediaframeworks_gpuimage_adapter_GLESNativeTools


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yy_mobile_hardwareencoder_softwareencoder_NativeJniCall
 * Method:    glReadPixelWithJni
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_yy_mediaframeworks_gpuimage_adapter_GLESNativeTools_glReadPixelWithJni
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
